name: ci:cd

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install Yandex Cloud Go SDK
        run: go get github.com/yandex-cloud/go-genproto/yandex/cloud/...

      - name: Initialize Terraform
        run: terraform init -input=false
        working-directory: terraform

      - name: Set Yandex Cloud token
        run: echo "${{ secrets.YANDEX_CLOUD_TOKEN }}" > yandex_cloud_token.txt
        working-directory: terraform

      - name: Plan Terraform changes
        run: terraform plan -out=terraform.plan -input=false -var-file=yandex_cloud_token.txt
        working-directory: terraform

      - name: Apply Terraform changes
        run: terraform apply -auto-approve -input=false
        working-directory: terraform

      - name: Output Terraform outputs
        run: terraform output
        working-directory: terraform