name: ci:cd

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - fedora-latest
          - arch-latest
